stages:
  - test

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  JAX_PLATFORM_NAME: cpu

cache:
  key: pip-cache
  paths:
    - .cache/pip

unit_tests:
  stage: test
  image: python:3.11
  script:
    - pip install -U pip
    # Force upgrade the JAX stack to ensure compatibility
    - pip install -U jax jaxlib quax quax-blocks unxt
    - pip install -e .
    - pip install pytest
    - pytest
    